export const WsEvent = {
  client: {
    messageSend: 'message.send',
    messageEdit: 'message.edit',
    messageDelete: 'message.delete',
    roomJoin: 'room.join',
    roomLeave: 'room.leave',
    presencePing: 'presence.ping',
    syncSince: 'sync.since',
  },
  server: {
    messageNew: 'message.new',
    messageEdited: 'message.edited',
    messageDeleted: 'message.deleted',
    roomMemberAdded: 'room.member.added',
    roomMemberRemoved: 'room.member.removed',
    roomRoleChanged: 'room.role.changed',
    roomBanned: 'room.banned',
    roomInvitationNew: 'room.invitation.new',
    roomDeleted: 'room.deleted',
    friendRequestNew: 'friend.request.new',
    friendRequestAccepted: 'friend.request.accepted',
    friendRemoved: 'friend.removed',
    userBanned: 'user.banned',
    dmFrozen: 'dm.frozen',
    presenceUpdate: 'presence.update',
    unreadChanged: 'unread.changed',
    reportNew: 'report.new',
    reportResolved: 'report.resolved',
    reportDismissed: 'report.dismissed',
    error: 'error',
  },
} as const;
