/**
 * Types + repository port for EPIC-08 attachments. Mirrors messages/rooms
 * pattern — port in its own file so service + TCP specs import the types
 * without pulling Drizzle/env chain.
 */

/** Row returned by repo. `id` is UUID. `messageId` nullable (attachment
 *  lives independently once `messages.id` is SET NULL by retention). */
export interface AttachmentRow {
  id: string;
  roomId: number | null;
  dmId: number | null;
  messageId: bigint | null;
  uploaderId: number;
  filename: string;
  mime: string;
  sizeBytes: number;
  path: string;
  comment: string | null;
  isImage: boolean;
  createdAt: Date | null;
}

/** Input for the initial upload row. Scope XOR enforced by service. */
export interface CreateAttachmentInput {
  id: string; // UUID generated by caller (FS layout needs it)
  roomId: number | null;
  dmId: number | null;
  uploaderId: number;
  filename: string;
  mime: string;
  sizeBytes: number;
  path: string;
  comment: string | null;
  isImage: boolean;
}

export interface BindAttachmentsInput {
  attachmentIds: string[];
  messageId: bigint;
  uploaderId: number; // must match attachment's uploader
  scope: { roomId: number } | { dmId: number };
}

export interface AttachmentsRepositoryPort {
  /** Persist the upload row (filesystem write already done by service). */
  insertAttachment(input: CreateAttachmentInput): Promise<AttachmentRow>;

  findById(id: string): Promise<AttachmentRow | null>;

  /** Listing per message — used on history fetch to hydrate bubble attachments. */
  findByMessageId(messageId: bigint): Promise<AttachmentRow[]>;

  /**
   * Bind a set of orphan attachments (messageId IS NULL) to a newly-created
   * message. Enforces: same uploader AND same scope (roomId or dmId) AND
   * not already bound. Returns bound rows. Ids that don't match are ignored
   * silently — caller can diff the returned ids vs requested to detect drift.
   */
  bindAttachmentsToMessage(input: BindAttachmentsInput): Promise<AttachmentRow[]>;

  /** True if user is one of the dm_channel's two participants. */
  isDmParticipant(dmId: number, userId: number): Promise<boolean>;
}

export const ATTACHMENTS_REPOSITORY = 'ATTACHMENTS_REPOSITORY';
